#!/usr/bin/env python3
"""Build baby-names/names.js from the US Social Security Administration baby names data.

Source: https://www.ssa.gov/oact/babynames/limits.html ("National data", names.zip).
SSA blocks scripted downloads, so download names.zip in a browser, then run:

    python3 baby-names/scripts/build_names.py ~/Downloads/names.zip

The input can be the zip itself or a folder of the yobYYYY.txt files inside it.
Names are ranked by total births over the most recent YEARS years, and the top
TOP_N per sex are kept, most popular first.
"""

import argparse
import re
import zipfile
from collections import Counter
from pathlib import Path

YEARS = 5
TOP_N = 1000
OUT = Path(__file__).resolve().parent.parent / "names.js"


def read_year_files(source: Path) -> dict[int, str]:
    """Return {year: file contents} for every yobYYYY.txt in a zip or folder."""
    files = {}
    if source.is_dir():
        for path in source.glob("yob*.txt"):
            files[int(path.stem[3:])] = path.read_text()
    else:
        with zipfile.ZipFile(source) as zf:
            for name in zf.namelist():
                m = re.fullmatch(r"(?:.*/)?yob(\d{4})\.txt", name)
                if m:
                    files[int(m.group(1))] = zf.read(name).decode()
    if not files:
        raise SystemExit(f"No yobYYYY.txt files found in {source}")
    return files


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("source", type=Path, help="SSA names.zip, or a folder of yobYYYY.txt files")
    parser.add_argument("--years", type=int, default=YEARS, help=f"recent years to total (default {YEARS})")
    parser.add_argument("--top", type=int, default=TOP_N, help=f"names to keep per sex (default {TOP_N})")
    args = parser.parse_args()

    files = read_year_files(args.source)
    years = sorted(files)[-args.years:]
    totals = {"M": Counter(), "F": Counter()}
    for year in years:
        for line in files[year].splitlines():
            if line.strip():
                name, sex, count = line.strip().split(",")
                totals[sex][name] += int(count)

    def block(sex: str) -> str:
        names = [name for name, _ in totals[sex].most_common(args.top)]
        lines, line = [], ""
        for name in names:
            if line and len(line) + len(name) + 1 > 88:
                lines.append(line)
                line = ""
            line = f"{line} {name}" if line else name
        lines.append(line)
        return "\n".join(lines)

    span = f"{years[0]}–{years[-1]}" if len(years) > 1 else str(years[0])
    OUT.write_text(
        "// Generated by scripts/build_names.py from US SSA baby names data — do not edit by hand.\n"
        f"// Top {args.top} names per sex by total births, {span}, most popular first.\n"
        "window.BASE_NAMES = {\n"
        f"  boy: `\n{block('M')}\n  `,\n"
        f"  girl: `\n{block('F')}\n  `,\n"
        "};\n"
    )
    print(f"Wrote {OUT} ({span}, top {args.top} per sex)")


if __name__ == "__main__":
    main()
