// Generated by scripts/build_names.py from US SSA baby names data — do not edit by hand.
// Top 1000 names per sex by total births, 2021–2025, most popular first.
window.BASE_NAMES = {
  boy: `
Liam Noah Oliver James Elijah Henry Theodore William Lucas Mateo Benjamin Levi Jack
Sebastian Daniel Michael Samuel Ethan Ezra Alexander Asher Leo Owen John Hudson Luca
Jackson Joseph David Mason Julian Elias Luke Matthew Jacob Logan Wyatt Gabriel Dylan
Aiden Thomas Grayson Maverick Isaac Santiago Anthony Carter Miles Cooper Jayden Charles
Josiah Caleb Ezekiel Isaiah Christopher Lincoln Nathan Joshua Roman Nolan Andrew Waylon
Angel Cameron Wesley Adrian Bennett Kai Brooks Weston Aaron Ian Thiago Axel Beau Rowan
Jaxon Christian Eli Silas Jonathan Ryan Everett Leonardo Robert Jeremiah Walker Micah
Jose Colton Easton Enzo Parker Theo Landon Gael August Adam Luka Jordan Jameson Xavier
Dominic Austin Myles Amir Nicholas Jace Hunter Atlas Damian River Greyson Carson Emmett
Kayden Vincent Adriel Archer Arthur Harrison Declan Ryder Milo Giovanni Sawyer Connor
Lorenzo Emiliano Jasper Jonah Jaxson George Luis Evan Diego Nathaniel Zion Bryson Graham
Calvin Legend Carlos Kingston Jason Juan Dean Malachi Leon Chase Cole Matteo Elliot Jude
Ace Ivan Arlo Braxton Jayce Dawson Hayden Rhett Ashton Brayden Elliott Max Jesus Charlie
Amari Ryker Maxwell Antonio Zachary Judah Beckett Emilio Emmanuel Tyler Matias Alan
Bentley Felix Nicolas Kaiden Camden Ayden Beckham Jesse Tucker Barrett Finn Hayes Callum
Messiah Kevin Maddox Justin Alejandro Miguel Jett Stetson Zayden Peter Alex Timothy
Andres Knox Abraham Brody Xander Victor Adonis Joel Oscar Abel Caden Brandon Edward
Patrick Richard Griffin Nico Gavin Grant Tate Karter Riley Rafael Kyrie Malakai Eric
Elian Avery Kairo Louis Simon Marcus Tristan Blake Rory Nash Mark Lukas Javier Aziel
Eithan Tatum Dallas Cohen Colt Israel Steven Jeremy King Crew Lane Omar Paul Zayn Lennox
Kash Remington Ronan Walter Emerson Kaleb Muhammad Milan Kenneth Phoenix Ismael Paxton
Holden Preston Zane Atticus Colter Callan Tobias Kayson Cash Bryce Derek Ellis Cade
Kaden Jax Jorge Malcolm Maximus Maximiliano Bodhi Finley Warren Cyrus Jaziel Otto
Clayton Brady Hendrix Aidan Kyler Francisco Jensen Bryan Josue Angelo Cody Brian Reid
Martin Niko Colin Romeo Dante Harvey Cruz Ali Jaylen Damien Andre Gideon Saint Erick
Cayden Colson Cristian Dakota Joaquin Cairo Koa Orion Bowen Leonel Zyaire Ezequiel
Manuel Baker Casey Wade Khalil Anderson Zander Sullivan Archie Spencer Daxton Jaden Kade
Briggs Bradley Fernando Onyx Ari Karson Luciano Raymond Eduardo Brantley Mathias Stephen
Shepherd Titus Ricardo Russell Sonny Cesar Julius Killian Desmond Chance Rylan Marshall
Prince Edwin Banks Hector Ares Sterling Jared Bodie Kamari Remy Jay Marco Travis Shiloh
Kohen Odin Mario Rhys Dariel Kane Franklin Callahan Baylor Kobe Wilder Ibrahim Lawson
Grady Iker Santino Sergio Kashton Raiden Jake Kameron Winston Royal Pablo Forrest Hugo
Malik Oakley Armani Nasir Apollo Tyson Clark Sean Wells Sage Kyle Tanner Reed Gunner
Pedro Kylo Zayne Solomon Nehemiah Kian Hank Johnny Noel Gianni Royce Edgar Sutton Corbin
Augustus Damon Alijah Esteban Matthias Koda Francis Isaias Quinn Raphael Devin Kieran
Fabian Finnegan Kyson Lewis Frederick Ronin Benson Eden Frank Erik Donovan Moshe
Leonidas Bo Adan Tripp Collin Jalen Callen Kendrick Tadeo Uriel Sylas Ruben Troy Alexis
Lucca Jeffrey Dalton Asa Johnathan Garrett Eliam Jasiah Reece Marcelo Andy Marcos Zaire
Miller Caiden Valentino Ford Leland Philip Rowen Mack Rocco Conrad Denver Memphis
Emanuel Jaiden Kaison Yusuf Leandro Kylian Alonzo Kason Kayce Major Ayaan Lucian Rodrigo
Makai Porter Moses Seth Kasen Camilo Soren Deacon Gregory Roberto Kaysen Ridge Hezekiah
Pierce Drew Kolton Boone Jaxton Zaiden Bruce Atreus Mohamed Lawrence Ariel Samson
Alessandro Dominick Dax Rome Enrique Moises Roy Cassius Saul Zachariah Allen Jonas Kylan
Princeton Jamir Ledger Morgan Azariah Jamari Armando Shane Rio Dorian Zain Trevor
Jayceon Lian Maximilian Arjun Hamza Nikolai Kenzo Johan Amiri Omari Keegan Scott Braylen
Peyton Izaiah Mohammad Clay Keanu Augustine Gunnar Cillian Ronald Julio Lionel Phillip
Elio Sincere Kaizen Jase Emir Kamden Shawn Albert Raul Ozzy Jayson Rayan Gerardo Anakin
Musa Fletcher Danny Jamie Arturo Jaime Ander Colby Samir Conor Krew Maximo Boston
Caspian Davis Alden Braylon Tru Louie Cannon Brixton Taylor Reese Gustavo Mohammed Yosef
Ocean Roland Emmitt Marvin Cassian Reign Westin Jamison Corey Nikolas Vicente Zakai
Layton Chaim Amos Creed Huxley Donald Sam Otis Dexter Harlan Layne Quincy Mac Julien
Finnley Mauricio Eliseo Azriel Drake Salem Ahmad Ryland Dustin Aarav Leonard Kyro Kareem
Zeke Abram Bellamy Zaid Chris Ahmed Abdiel Uriah Wilson Dennis Houston Duke Truett Dario
Chandler Westley Conner Jakari Case Bruno Cal Mylo Madden Hassan Briar Kyaire Lachlan
Raylan Carmelo Tommy Santana Keith Lee Darius Jakai Kyree Eliel Vincenzo Quentin Amias
Nathanael Zayd Marcel Trace Koen Axton Tomas Gage Clyde Wayne Skyler Salvador Chosen
Azrael Rhodes Trey Forest Zyair Ambrose Lennon Aron Riggs Cayson Junior Derrick Flynn
Rayden Bridger Azael Alberto Valentin Rocky Rex Alfredo Harry Roger Benicio Enoch
Jefferson Tony Magnus Brycen Wylder Brock Misael Ty Issac Evander Lochlan Jaxxon Edison
Yehuda Kannon Hugh Idris Blaze Aries Remi Emery Dilan Casen Sevyn Dillon Watson Alvaro
Alvin Crue Avi Wes Noe Landen Nelson Zahir Kaiser Alonso Douglas Ray Bjorn Robin Cason
Dakari Loyal Franco Ben Zamir Aryan Neil Brayan Avyaan Keaton Boden Quinton Rudy Yahya
Orlando Jimmy Alec Ramon Rey Abdullah Jerry Trenton Bear Rohan Legacy Santos Stanley
Lance Yousef Nixon Jagger Kiaan Jedidiah Yahir Grey Gatlin Thaddeus Elisha Everest
Jiraiya Kenji Westyn Guillermo Mustafa Aden Kingsley Ricky Dereck Eddie Waylen Melvin
Dutton Justice Calum Ayan Emory Langston Mitchell Bode Aurelio Marcellus Reuben Byron
Karim Ryatt Chozen Dane Joziah Kyren Allan Landyn Ira Yael Murphy Fisher Castiel Alfred
Damir Seven Mccoy Jahmir Eiden Anders Curtis Ezrah Teo Leroy Ernesto Vihaan Arian Joe
Mathew Ignacio Devon Gian Felipe Dash Ishaan Joey Judson Jones Jeremias Jon Jesiah
Brodie Eugene Jericho Leif Kylen Zyon Wesson Kellan Kolson Jasiel Khai Zechariah Kenai
Kaisen Colten Brendan Alistair Izan Zev Ozias Salvatore Damari Yisroel Coleson Ameer
Benedict Jrue Heath Van Darren Kellen Shepard Leighton Matheo Adler Titan Axl Khari
Campbell Jairo Ermias Alfonso Asaiah Massimo Agustin Khalid Maurice Kase Colsen Cullen
Kabir Benny Harold Abner Shmuel Kolter Henrik Zavier Eren Harlem Darwin Darian Yadiel
Mordechai Talon Wallace Stefan Izael Jadiel Meir Aldo Teddy Boaz Khaza Thatcher Jovanni
Randy Kelvin Larry Lucien Demetrius Cain Jasai Ulises Osiris Imran Azaiah Harley Stone
Brennan Eliezer Vance Bronson Neo Jireh Kartier Korbin Mekhi Foster Yaakov Alaric Ahmir
Ephraim Aspen
  `,
  girl: `
Olivia Emma Charlotte Amelia Sophia Mia Isabella Ava Evelyn Harper Luna Sofia Camila
Eleanor Elizabeth Violet Gianna Scarlett Aurora Chloe Hazel Nora Aria Penelope Emily
Lily Ella Ellie Avery Abigail Eliana Mila Layla Isla Nova Zoe Madison Grace Lucy Ivy
Willow Riley Emilia Naomi Stella Elena Victoria Valentina Hannah Zoey Leah Lillian Maya
Delilah Paisley Addison Leilani Sadie Sophie Josephine Genesis Lainey Ruby Madelyn Alice
Natalie Everly Claire Kinsley Adeline Eloise Audrey Autumn Emery Kennedy Iris Aaliyah
Vivian Clara Quinn Caroline Brooklyn Maria Liliana Ayla Jade Maeve Hailey Anna Madeline
Eden Athena Savannah Lyla Sarah Lydia Cora Gabriella Allison Melody Natalia Bella Ariana
Aubrey Daisy Serenity Josie Skylar Millie Raelynn Lucia Eva Nevaeh Parker Rylee Hadley
Juniper Eliza Julia Rose Samantha Alaia Margaret Amara Piper Charlie Brielle Cecilia
Remi Everleigh Elliana Melanie Sienna Georgia Mary Esther Ailany Alina Arya Peyton
Catalina Magnolia Adalynn Valerie Emersyn Isabelle Juliette Sloane Summer Ashley Margot
Freya Kehlani Sage Ember Emerson Valeria Ximena Amira Genevieve Isabel Oakley June
Oaklynn Blakely Mackenzie Anastasia Elsie Amaya Katherine Alana Olive Reese Alani Reagan
Rosalie Ruth Callie Ariella River Brianna Bailey Andrea Hallie Arianna Kaylee Gemma
Jasmine Sara Ada Kylie Phoebe Adalyn Evangeline Myla Molly Kaia Lilah Annie Alexandra
Norah Sutton Noelle Wrenley Lila Wren Khloe Alaina Journee Faith Arabella Amy Presley
Adaline Zara Brynlee Lia Vera Daphne Ana Blake Aspen Vivienne Tatum Haven Saylor Blair
Aliyah Lennon Kaylani Stevie Diana Harmony Zuri Juliana Selena Nyla Celeste Delaney
Ryleigh Kimberly Gracie Alora Lilly Leila Rachel Elise Mariana Morgan Camille Miriam
Kailani Kiara Rowan Dahlia Aitana Collins Lilith Elaina Jane Mabel Sawyer Lola Lucille
Leia Kamila Harlow Lena Ophelia Daniela Taylor Dakota Palmer Gia Londyn Noa Cataleya
Milani Angela Evie Marley Jordyn Octavia Ariel Adelaide Talia Celine Finley Elianna
Juliet Kali Hope Sydney Brooke Malia Maisie Selah Maggie Aubree Alayna Rory Teagan
Adelyn Shiloh Kayla Tessa Samara London Vanessa Kendall Evelynn Rosemary Angelina Joanna
Gabriela Rebecca Amari Laila Amina Nina Journey Annabelle Catherine Amora Thea Luciana
Nayeli Poppy Alyssa Antonella Camilla Payton Esme Adriana Scottie Alessia Mya Nicole
Paige Julianna Mckenna Jocelyn Danna Trinity Fatima Ailani Lauren Charlee Harley Winter
Ariyah Alivia Hayden Azalea Briella Dream Kalani Francesca Serena Logan Heidi Giselle
Meadow Rosie Regina Madilyn Phoenix Leighton Jayla Laura Adelina Viviana Malani
Esmeralda Alayah Fiona Sabrina Alaya Mariah Raegan Gracelynn Frances Navy Gwendolyn
Aurelia Wynter Brooklynn Anaya Emory Sylvia Elaine Hattie Adelynn Lilliana Raven Brynn
Raya Melissa Julieta Alanna Sylvie Aniyah Aisha Lana Demi Reign Aylin Astrid Willa
Colette Michelle Kira Alessandra Mira Veronica Matilda Raelyn Alexandria Annalise
Mckenzie Madeleine Maryam Itzel Everlee Elle Alexis Carmen Liana Elisa Cali Arielle
Helen Lorelai Nylah Sarai Elora Joy Gracelyn Alicia Remington Helena Miracle Maia Holly
Anya Carolina Charli Salem Camryn Saige Makayla Mallory Daleyza Lorelei Izabella Dorothy
Sunny Daniella Destiny Zariah Skye Bianca Felicity Makenna Amiyah Xiomara Rylie Katalina
Emely Alison Ivory Scarlet Bonnie Alma Haisley Lyra Kate Opal Maddison Amanda Miley Emmy
Macie Oaklee Avianna Nadia Armani Marlee Cameron Mylah Arleth Danielle Cassidy Kaliyah
Brinley Allie Stephanie Leona Madelynn Renata Paris Kora Briar Blaire Ari Heaven Maren
Lexi Jordan Carter Edith Fernanda Angel Elodie Mae Jimena Ainsley Clementine Ariah
Florence Meredith Lyric Amirah Imani April Jazlyn Calliope Kamryn Monroe Jennifer
Jacqueline Anahi Nalani Hanna Gabrielle Cecelia Murphy Legacy Virginia Emelia Melany
Royalty Paislee Wrenlee Jolene Amber Eve Makenzie Faye Jessica Mariam Kyla Estella
Maliyah Ariya Amalia Keira Alondra Bristol Elowyn Beatrice Frankie Dayana Briana Katie
Maxine Sierra Emerie Kenzie Marceline Averie Winnie Lilian Kinley Alia Ivanna Oaklyn
Reyna Margo Lylah Oakleigh Louise Mara Alejandra Yara Zahra Romina Kayleigh Holland
Capri Lina Sevyn Miranda Kataleya Yaretzi Rhea Hadassah Mina Reina Nellie Anne Skyler
Vienna Rosalia Chaya Amaia Elliott Myra Kennedi Leyla Indie Aliana Charleigh Marie
Shelby Noemi Emberly Priscilla Tiana Mavis Iyla Ryan Zariyah Alexa Jaylani Abby Noah
Halo Della Cassandra Sasha Journi Jovie Davina Marina Gloria Remy Nia Amoura Eileen Cleo
Amani Azariah Braelynn Angelica Jenna Siena Melina Thalia Rosa Addilyn Dallas Kaitlyn
Lennox Aleena Ellianna Dylan Leslie Halle Mckinley Sariyah Flora Irene Aylani Analia
Alisson Adley Estrella Maci Michaela Clover Madilynn Karsyn Kathryn Estelle Isabela
Laney Kelsey Kensley Haley Jaliyah Mikayla Jazmin Macy Aliza Milan Selene Ellis Galilea
Arlette Sloan Khaleesi Keilani Ila Angie Erin Aya Freyja Martha Aviana Nola Jream
Bethany Marlowe Adhara Zelda Laurel Kyra Charley Christina Lara Coraline Violeta Janelle
Adrianna Marilyn Goldie Emmie Kendra Jemma Lillie Penny Jenesis Megan Rivka Dani Hana
Chelsea Karla Kenna Ezra Fallon Karina Monica Julie Chana Leilany Andi Persephone
Loretta Malaysia Aileen Arlet Aleah Bridget Theodora Lakelynn Louisa Marigold Yareli
Rayna Kiana Dior Jamie Noor Alena Malaya Birdie Lottie Jayleen Kylee Whitley Taytum
Lenora Dulce Drew Liv Cheyenne Belen Treasure Pearl Promise Marisol Emerald Ramona Naya
Zaylee Milana Azaria Aila Paulina Paula Gwen Lacey Baylor Skyla Johanna Amayah Sky
Bellamy Novah Milena Samira Henley Brynleigh Nala Veda Celia Jessie Lea Denver Adele
Adalee Carly Kori Robin Novalee Valery Zaniyah Georgina Solana Ocean Savanna Araceli
Billie Hunter Mercy Marleigh Amelie Meilani Kimber Livia Kelly Elyse Giana Ashlyn
Janiyah Aliya Zaria Rosalina Iliana Mikaela Scout Berkley Linda Liberty Ensley Elina
Kinslee Love Waverly Winona Anais Sol Nyomi Seraphina Marianna Stormi Teresa Maisy
Lakelyn Miller Dalia Jolie Rayne Joelle Hadlee Kallie Inaya Brittany Giuliana Judith
Keyla Vada Alaiya Luz Aspyn Amaris Zendaya Ayleen Elliot Greta Cynthia Zainab Zora
Kassidy Anika Alexia Khalani Tiffany Lilianna Rowyn Roselyn Ashlynn Luella Alianna
Emberlynn Magdalena Kamiyah Katelyn Kaiya Jazmine Allyson August Elia Deborah Giovanna
Baylee Andie Madisson Bria Zayla Soleil Indy Rebekah Salma Chandler Xyla Harmoni Harlee
Tallulah Jianna Paloma Cadence Barbara Luisa Kara Maddie Kai Annika Cielo Zoya Laylani
Indigo Karter Braelyn Ruthie Kamari Leanna Lilyana Raina Jayda Artemis Emiliana Hayley
Bailee Kahlani Yasmin Emmeline Rosalyn Nataly Bexley Aura Rosalee Clare Kailany Madalyn
Eleanora Saoirse Guinevere Avani Jada Yamileth Lilia Natasha Nancy Amiri Simone Lisa
Jaycee Etta Campbell Sarahi Malayah Elisabeth Sariah Kairi Emmalyn Keziah Micah Ainhoa
Saanvi Tru Lyanna Elouise Neriah Justice Aubrie Ayah Azari Soraya Angelique Violette
Aubriella Brylee Ayra Julissa Quincy Reya Avayah Raquel Princess Arely Celina Tilly Ivey
Madisyn Laylah Elsa Nori
  `,
};
